### ISSUE TITLE
主题使用不了

### ISSUE THREAD

**Issue by CN-DXTZ** [Chorer/hexo-theme-PureBlue#1]
主题使用报错
![image](https://user-images.githubusercontent.com/32838018/55820461-c0559180-5b2d-11e9-8653-3f061dd38a7f.png)

**Comment by CN-DXTZ** [comment]
OK，我知道了这个问题是没安装插件[hexo-wordcount](https://github.com/willin/hexo-wordcount)，可以通过以下方式解决：
npm i --save hexo-wordcount
不过出现了新的问题
![image](https://user-images.githubusercontent.com/32838018/55845297-e56cf300-5b73-11e9-9c61-2822acf42c1e.png)

**Comment by CN-DXTZ** [comment]
OK，我不熟悉前端，不过应该是about和share部分还没完成，因为会出现两个报错如下：
`failed to locate @import file _partial/about.styl`
`failed to locate @import file _partial/share.styl`
我的解决方案是暂时注释掉这两个文件，
在 \themes\PureBlue\source\css\style.syl 文件里：
`//@import "_partial/about";`
`//@import "_partial/share";`

**Comment by Chorer** [comment]
不好意思，一直没看issue，以为没用户。。这个问题我明天看下。

**Comment by Chorer** [comment]
@CN-DXTZ  不好意思，一直没注意看issue，以为主题没人用。第一个问题是统计字数的，开启的话得安装插件;第二个问题，因为about页是自己写md的，内容也是自己定，所以统一的样式不一定适合每个人，项目里我就没放about.styl文件了，但是忘记去掉引入的语句，你注释掉也可以的。about页我过几天有空了修复一下，最近考试。。

**Comment by Chorer** [comment]
@CN-DXTZ  下载最新的 release https://github.com/Chorer/hexo-theme-PureBlue/releases
