### ISSUE TITLE
左侧分享按钮不显示

### ISSUE THREAD

**Issue by polojucy** [Chorer/hexo-theme-PureBlue#2]
我的左侧分享按钮不显示，请问是需要安装其他插件吗

**Comment by Chorer** [comment]
不用安装的，这个是动态导入。你需要先去 [Addthis 官网](https://www.addthis.com/)申请一个 pubid，然后在主题根目录下的 `config.yml` 文件中填入（有标注），同时设置  `enable`  为  `true`，这时候插件就自动导入了，关于样式也是在 Addthis 的官网配置。
